noun = input("Enter a noun: ")
verb = input("Enter a verb: ")
type_of_liquid = input("Enter a type of liquid: ")
animal = input("Enter an animal: ")
type_of_food1 = input("Enter a type of food: ")
plural_noun1 = input("Enter a plural noun: ")
plural_noun2 = input("Enter another plural noun: ")
plural_noun3 = input("Enter another plural noun: ")
num = input("Enter a number: ")
type_of_food2 = input("Enter another type of food: ")
plural_noun4 = input("Enter another plural noun: ")
adjective1 = input("Enter an adjective: ")
plural_noun5 = input("Enter another plural noun: ")
adjective2 = input("Enter another adjective: ")
type_of_food3 = input("Enter another type of food: ")
plural_noun6 = input("Enter another plural noun: ")
place = input("Enter a place: ")

print("the daily schedule of an average 6th grade teacher".upper())
print("6:00 a.m.: Wake up to the sound of the " + noun + " beeping. " + verb.title() + " out of bed and go immediately to the " + type_of_liquid + "-maker. Ahhhh...much better!")
print("7:30 a.m.: Walk the " + animal + ", eat " + type_of_food1 + " for breakfast, and drive to school while listening to " + plural_noun1 + " on the radio.")
print("9:00 a.m.: First period! Teach " + plural_noun2 + ", hand back pop " + plural_noun3 + ", and answer questions about how to get extra credit.")
print("12:00 p.m.: Only " + num + " minute(s) for lunch! Eat leftover " + type_of_food2 + " as quickly as possible. And drink another cup of " + type_of_liquid + " of course!")
print("3:00 p.m.: School day is over for the " + plural_noun4 + " but the " + adjective1 + " work has only just begun. Grade " + plural_noun5 + ", write assignments, and hang " + adjective2 + " decorations in classroom.")
print("5:00 p.m.: Drive home, heat up " + type_of_food3 + " for dinner in the microwave, fall asleep while watching The Real " + plural_noun6.title() + " of (the) " + place.title() + " on television!")